# Generated by Django 4.2.9 on 2024-01-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], max_length=2)),
                ('common_name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(max_length=100)),
                ('bird_description', models.TextField(blank=True)),
                ('current_status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], default='Least Concern', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='classifiedimage',
            old_name='uploaded_at',
            new_name='classified_at',
        ),
        migrations.RemoveField(
            model_name='classifiedimage',
            name='predicted_class',
        ),
        migrations.AddField(
            model_name='classifiedimage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiedimage',
            name='predicted_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.birdspecies'),
        ),
    ]
