# Generated by Django 4.2.9 on 2024-01-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_birdspecies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='current_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], max_length=2),
        ),
    ]
