# Generated by Django 4.2.9 on 2024-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_birdspecies_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='status_code',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], max_length=10),
        ),
    ]
