# Generated by Django 4.2.9 on 2024-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_birdspecies_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdspecies',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
